import GET_PERSONAL_DETAILS_QUERY from "./GET_PERSONAL_DETAILS_QUERY";
import GET_USER_LOGIN_TOKEN_QUERY from "./GET_USER_LOGIN_TOKEN_QUERY";
export { GET_PERSONAL_DETAILS_QUERY, GET_USER_LOGIN_TOKEN_QUERY };
