export const CONFETTI_ANIMATION = "CONFETTI_ANIMATION";
export const CONFETTI_ANIMATION_SUCCESS = "CONFETTI_ANIMATION_SUCCESS";
export const CONFETTI_ANIMATION_ERROR = "CONFETTI_ANIMATION_ERROR";

export const INIT_APP = "INIT_APP";
export const INIT_APP_SUCCESS = "INIT_APP_SUCCESS";

export const ACTIVATE_ANALYTICS = "ACTIVATE_ANALYTICS";
export const ACTIVATE_ANALYTICS_SUCCESS = "ACTIVATE_ANALYTICS_SUCCESS";

export const TRACK_ANALYTICS = "TRACK_ANALYTICS";
export const TRACK_ANALYTICS_SUCCESS = "TRACK_ANALYTICS_SUCCESS";

export const UPDATE_ENTIRE_RESUME = "UPDATE_ENTIRE_RESUME";
export const UPDATE_ENTIRE_RESUME_SUCCESS = "UPDATE_ENTIRE_RESUME_SUCCESS";
export const UPDATE_ENTIRE_RESUME_ERROR = "UPDATE_ENTIRE_RESUME_ERROR";

export const GET_USER_LOGIN_TOKEN = "GET_USER_LOGIN_TOKEN";
