export const CONFETTI_ANIMATION = "CONFETTI_ANIMATION";
export const CONFETTI_ANIMATION_SUCCESS = "CONFETTI_ANIMATION_SUCCESS";
export const CONFETTI_ANIMATION_ERROR = "CONFETTI_ANIMATION_ERROR";

export const INIT_APP = "INIT_APP";
export const INIT_APP_SUCCESS = "INIT_APP_SUCCESS";

export const ACTIVATE_ANALYTICS = "ACTIVATE_ANALYTICS";
export const ACTIVATE_ANALYTICS_SUCCESS = "ACTIVATE_ANALYTICS_SUCCESS";
